export const categories = [
  {
    id: '1',
    name: 'Burgers',
    description: '',
    imageLink: require('~/resources/images/burger.png'),
  },
  {
    id: '2',
    name: 'Milk Tea',
    description: '',
    imageLink: require('~/resources/images/milk-tea.png'),
  },
  {
    id: '3',
    name: 'Western',
    description: '',
    imageLink: require('~/resources/images/western.png'),
  },
  {
    id: '4',
    name: 'Pizzas',
    description: '',
    imageLink: require('~/resources/images/pizza.png'),
  },
  {
    id: '5',
    name: 'Sweets',
    description: '',
    imageLink: require('~/resources/images/sweet.png'),
  },
  {
    id: '6',
    name: 'Salads',
    description: '',
    imageLink: require('~/resources/images/salad.png'),
  },
  {
    id: '7',
    name: 'Chickens',
    description: '',
    imageLink: require('~/resources/images/chicken.png'),
  },
  {
    id: '8',
    name: 'Coffee',
    description: '',
    imageLink: require('~/resources/images/coffee.png'),
  },
  {
    id: '9',
    name: 'Diet',
    description: '',
    imageLink: require('~/resources/images/diet.png'),
  },
  {
    id: '10',
    name: 'Indian',
    description: '',
    imageLink: require('~/resources/images/indian.png'),
  },
  {
    id: '11',
    name: 'Chinese',
    description: '',
    imageLink: require('~/resources/images/chinese.png'),
  },
  {
    id: '12',
    name: 'Japanese',
    description: '',
    imageLink: require('~/resources/images/japanese.png'),
  },
];

export const restaurants = [
  {
    id: '1',
    name: 'KFC',
    wallpaper: require('~/resources/images/kfc-wallpaper.png'),
    logo: require('~/resources/images/kfc-logo.png'),
    phone: '0123456789',
    email: 'testdata@gmai.com',
    rating: '4.8',
    address: '69 Tân Lập, Dĩ An, Bình Dương',
  },
  {
    id: '2',
    name: 'Restaurant 2',
    wallpaper: require('~/resources/images/kfc-wallpaper.png'),
    logo: require('~/resources/images/kfc-logo.png'),
    phone: '0123456789',
    email: 'testdata@gmai.com',
    rating: '5.0',
    address: '69 Tân Lập, Dĩ An, Bình Dương',
  },
  {
    id: '3',
    name: 'Restaurant 3',
    wallpaper: require('~/resources/images/kfc-wallpaper.png'),
    logo: require('~/resources/images/kfc-logo.png'),
    phone: '0123456789',
    email: 'testdata@gmai.com',
    rating: '4.8',
    address: '69 Tân Lập, Đông Hòa, Dĩ An, Bình Dương',
  },
  {
    id: '4',
    name: 'Restaurant 4',
    wallpaper: require('~/resources/images/kfc-wallpaper.png'),
    logo: require('~/resources/images/kfc-logo.png'),
    phone: '0123456789',
    email: 'testdata@gmai.com',
    rating: '4.8',
    address: '69 Tân Lập, Đông Hòa, Dĩ An, Bình Dương',
  },
  {
    id: '5',
    name: 'Restaurant 5',
    wallpaper: require('~/resources/images/kfc-wallpaper.png'),
    logo: require('~/resources/images/kfc-logo.png'),
    phone: '0123456789',
    email: 'testdata@gmai.com',
    rating: '4.8',
    address: '69 Tân Lập, Đông Hòa, Dĩ An, Bình Dương',
  },
  {
    id: '6',
    name: 'KFC',
    wallpaper: require('~/resources/images/kfc-wallpaper.png'),
    logo: require('~/resources/images/kfc-logo.png'),
    phone: '0123456789',
    email: 'testdata@gmai.com',
    rating: '4.8',
    address: '69 Tân Lập, Đông Hòa, Dĩ An, Bình Dương',
  },
  {
    id: '7',
    name: 'Restaurant 2',
    wallpaper: require('~/resources/images/kfc-wallpaper.png'),
    logo: require('~/resources/images/kfc-logo.png'),
    phone: '0123456789',
    email: 'testdata@gmai.com',
    rating: '5.0',
    address: '69 Tân Lập, Đông Hòa, Dĩ An, Bình Dương',
  },
  {
    id: '8',
    name: 'Restaurant 3',
    wallpaper: require('~/resources/images/kfc-wallpaper.png'),
    logo: require('~/resources/images/kfc-logo.png'),
    phone: '0123456789',
    email: 'testdata@gmai.com',
    rating: '4.8',
    address: '69 Tân Lập, Đông Hòa, Dĩ An, Bình Dương',
  },
  {
    id: '9',
    name: 'Restaurant 4',
    wallpaper: require('~/resources/images/kfc-wallpaper.png'),
    logo: require('~/resources/images/kfc-logo.png'),
    phone: '0123456789',
    email: 'testdata@gmai.com',
    rating: '4.8',
    address: '69 Tân Lập, Đông Hòa, Dĩ An, Bình Dương',
  },
  {
    id: '10',
    name: 'Restaurant 5',
    wallpaper: require('~/resources/images/kfc-wallpaper.png'),
    logo: require('~/resources/images/kfc-logo.png'),
    phone: '0123456789',
    email: 'testdata@gmai.com',
    rating: '4.8',
    address: '69 Tân Lập, Đông Hòa, Dĩ An, Bình Dương',
  },
  {
    id: '11',
    name: 'KFC',
    wallpaper: require('~/resources/images/kfc-wallpaper.png'),
    logo: require('~/resources/images/kfc-logo.png'),
    phone: '0123456789',
    email: 'testdata@gmai.com',
    rating: '1.1',
    address: '69 Tân Lập, Đông Hòa, Dĩ An, Bình Dương',
  },
  {
    id: '12',
    name: 'Restaurant 2',
    wallpaper: require('~/resources/images/kfc-wallpaper.png'),
    logo: require('~/resources/images/kfc-logo.png'),
    phone: '0123456789',
    email: 'testdata@gmai.com',
    rating: '5.0',
    address: '69 Tân Lập, Đông Hòa, Dĩ An, Bình Dương',
  },
  {
    id: '13',
    name: 'Restaurant 3',
    wallpaper: require('~/resources/images/kfc-wallpaper.png'),
    logo: require('~/resources/images/kfc-logo.png'),
    phone: '0123456789',
    email: 'testdata@gmai.com',
    rating: '4.8',
    address: '69 Tân Lập, Đông Hòa, Dĩ An, Bình Dương',
  },
  {
    id: '14',
    name: 'Restaurant 4',
    wallpaper: require('~/resources/images/kfc-wallpaper.png'),
    logo: require('~/resources/images/kfc-logo.png'),
    phone: '0123456789',
    email: 'testdata@gmai.com',
    rating: '4.8',
    address: '69 Tân Lập, Đông Hòa, Dĩ An, Bình Dương',
  },
  {
    id: '15',
    name: 'Restaurant 5',
    wallpaper: require('~/resources/images/kfc-wallpaper.png'),
    logo: require('~/resources/images/kfc-logo.png'),
    phone: '0123456789',
    email: 'testdata@gmai.com',
    rating: '4.8',
    address: '69 Tân Lập, Đông Hòa, Dĩ An, Bình Dương',
  },
];

export const searchHistory = [
  'chicken',
  'salad',
  'Hồng trà Ngô Gia',
  'Cơm tấm Ngô Quyền',
  'Gong Cha',
];

export const offers = [
  {
    id: '1',
    voucherImageLink: require('~/resources/images/kfc-voucher.png'),
    logoLink: require('~/resources/images/kfc-logo.png'),
    owner: 'KFC Lê Văn Lương',
  },
  {
    id: '2',
    voucherImageLink: require('~/resources/images/kfc-voucher.png'),
    logoLink: require('~/resources/images/kfc-logo.png'),
    owner: 'Restaurant 2',
  },
  {
    id: '3',
    voucherImageLink: require('~/resources/images/kfc-voucher.png'),
    logoLink: require('~/resources/images/kfc-logo.png'),
    owner: 'Restaurant 3',
  },
  {
    id: '4',
    voucherImageLink: require('~/resources/images/kfc-voucher.png'),
    logoLink: require('~/resources/images/kfc-logo.png'),
    owner: 'Restaurant 4',
  },
  {
    id: '5',
    voucherImageLink: require('~/resources/images/kfc-voucher.png'),
    logoLink: require('~/resources/images/kfc-logo.png'),
    owner: 'Restaurant 5',
  },
  {
    id: '6',
    voucherImageLink: require('~/resources/images/kfc-voucher.png'),
    logoLink: require('~/resources/images/kfc-logo.png'),
    owner: 'Restaurant 5',
  },
  {
    id: '7',
    voucherImageLink: require('~/resources/images/kfc-voucher.png'),
    logoLink: require('~/resources/images/kfc-logo.png'),
    owner: 'Restaurant 5',
  },
  {
    id: '8',
    voucherImageLink: require('~/resources/images/kfc-voucher.png'),
    logoLink: require('~/resources/images/kfc-logo.png'),
    owner: 'Restaurant 5',
  },
];

export const products = [
  {
    id: '1',
    name: 'Classic Cheese Hamburger',
    image: require('~/resources/images/milk-tea.png'),
    price: '100.000',
    restaurantLogo: require('~/resources/images/kfc-logo.png'),
    restaurantName: 'KFC - Lê Văn Việt',
  },
  {
    id: '2',
    name: 'Simply Cheese with Sesame Seed bunsClassic Cheese Hamburger',
    image: require('~/resources/images/milk-tea.png'),
    price: '100.000',
    restaurantLogo: require('~/resources/images/kfc-logo.png'),
    restaurantName: 'KFC - Lê Văn Việt',
  },
  {
    id: '3',
    name: 'Classic Cheese Hamburger',
    image: require('~/resources/images/milk-tea.png'),
    price: '100.000',
    restaurantLogo: require('~/resources/images/kfc-logo.png'),
    restaurantName: 'KFC - Lê Văn Việt',
  },
  {
    id: '4',
    name: 'Simply Cheese with Sesame Seed bunsClassic Cheese Hamburger',
    image: require('~/resources/images/milk-tea.png'),
    price: '100.000',
    restaurantLogo: require('~/resources/images/kfc-logo.png'),
    restaurantName: 'KFC - Lê Văn Việt',
  },
  {
    id: '5',
    name: 'Classic Cheese Hamburger',
    image: require('~/resources/images/milk-tea.png'),
    price: '100.000',
    restaurantLogo: require('~/resources/images/kfc-logo.png'),
    restaurantName: 'KFC - Lê Văn Việt',
  },
  {
    id: '6',
    name: 'Simply Cheese with Sesame Seed bunsClassic Cheese Hamburger',
    image: require('~/resources/images/milk-tea.png'),
    price: '100.000',
    restaurantLogo: require('~/resources/images/kfc-logo.png'),
    restaurantName: 'KFC - Lê Văn Việt',
  },
  {
    id: '7',
    name: 'Classic Cheese Hamburger',
    image: require('~/resources/images/milk-tea.png'),
    price: '100.000',
    restaurantLogo: require('~/resources/images/kfc-logo.png'),
    restaurantName: 'KFC - Lê Văn Việt',
  },
  {
    id: '8',
    name: 'Simply Cheese with Sesame Seed bunsClassic Cheese Hamburger',
    image: require('~/resources/images/milk-tea.png'),
    price: '100.000',
    restaurantLogo: require('~/resources/images/kfc-logo.png'),
    restaurantName: 'KFC - Lê Văn Việt',
  },
  {
    id: '9',
    name: 'Classic Cheese Hamburger',
    image: require('~/resources/images/milk-tea.png'),
    price: '100.000',
    restaurantLogo: require('~/resources/images/kfc-logo.png'),
    restaurantName: 'KFC - Lê Văn Việt',
  },
  {
    id: '10',
    name: 'Simply Cheese with Sesame Seed bunsClassic Cheese Hamburger',
    image: require('~/resources/images/milk-tea.png'),
    price: '100.000',
    restaurantLogo: require('~/resources/images/kfc-logo.png'),
    restaurantName: 'KFC - Lê Văn Việt',
  },
];

export const orderedProducts = [
  {
    id: '1',
    image: require('~/resources/images/milk-tea.png'),
    name: 'Iced Toffee Nut Crunch Latte',
    addOnInfo: '100% Sugar, 100% Ice, Size Venti',
    quantity: '1',
    totalUnitPrice: '99.000',
  },
  {
    id: '2',
    image: require('~/resources/images/milk-tea.png'),
    name: 'Iced Toffee Nut Crunch Latte',
    addOnInfo: '100% Sugar, 100% Ice, Size Venti',
    quantity: '2',
    totalUnitPrice: '79.000',
  },
  {
    id: '3',
    image: require('~/resources/images/milk-tea.png'),
    name: 'Iced Toffee Nut Crunch Latte',
    addOnInfo: '100% Sugar, 100% Ice, Size Venti',
    quantity: '1',
    totalUnitPrice: '89.000',
  },
  {
    id: '4',
    image: require('~/resources/images/milk-tea.png'),
    name: 'Iced Toffee Nut Crunch Latte',
    addOnInfo: '100% Sugar, 100% Ice, Size Venti',
    quantity: '3',
    totalUnitPrice: '99.000',
  },
  {
    id: '5',
    image: require('~/resources/images/milk-tea.png'),
    name: 'Iced Toffee Nut Crunch Latte',
    addOnInfo: '100% Sugar, 100% Ice, Size Venti',
    quantity: '1',
    totalUnitPrice: '99.000',
  },
];
